// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Text    string `json:"text"`
	Comment string `json:"comment"`
}

type Todo struct {
	ID        string  `json:"id"`
	Text      string  `json:"text"`
	Comment   string  `json:"comment"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}

type UpdateTodoInput struct {
	ID      string `json:"id"`
	Text    string `json:"text"`
	Comment string `json:"comment"`
}
