name: Go

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: cd app && go build -v ./...

    - name: Lint
      uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.1"
      run: cd app && staticcheck ./...

    - name: Test
      run: cd app && go test -v ./...
